### PR TITLE
Add sample application data and remove specific google-services.json

### PR DESCRIPTION
**Pull request by timkrins**
Great library! I plugged together a few changes that should help people setting up the sample application.

- Removes author specific `google-services.json` and adds this file to `.gitignore`
- Adds example database information in `sample/sample-database.json`
- Adds example rules in `sample/sample-rules.json`
- Adds documentation in `README.md`

Cheers

### CODE REVIEW

**Comment by ashdavies** [comment]
Thanks for the addition @timkrins ! I had left the google services file so that Travis would still be able to run the tests (ordinarily this is highly ill-advised, but the project no longer exists), please modify `.travis.yml` to only build the library module and retarget the pull request to the develop branch

**Comment by timkrins** [comment]
Sorry man, I'll eventually get around to this, but not soon... I had to switch out of using Firebase.
(EU data protection... boo to Firebase DB only being available on US servers)
Cheers

**Comment by ashdavies** [comment]
Well depends on how you use it, Firebase offers an opt out for analytics collection which means you can comply with EU law (I work in Germany), and also has localised storage buckets which gives you the same

**Review by ashdavies — APPROVED** [review]
I'm going to approve this for merge after the Travis build being modified to only build the library and thus not being dependent on the sample module, I'll merge it in shortly. 

Thanks for contributing @timkrins !

**Pull request merged**
